"""Tag and StockTag models — AI-generated sector/industry classification.

Design decisions:
─────────────────
Tags are NORMALISED into their own table with a junction (StockTag) because:
1. Many stocks share the same tag ("auto ancillaries" may apply to 20 stocks).
   Without normalisation, we'd store "auto ancillaries" 20 times.
2. The Tag table is a controlled vocabulary — we can list all known tags,
   count how many stocks each tag has, and aggregate returns by tag.
3. The junction table (StockTag) records PROVENANCE: which screener triggered
   the tagging, when it happened, and whether it came from Gemini or manual input.

WHY source column?
- Tracks whether a tag was auto-generated by Gemini or manually assigned.
- Useful for auditing: if Gemini mis-tags a stock, you can filter to
  'gemini' source tags and review them.

WHY UniqueConstraint on (stock_id, tag_id)?
- A stock should never have the same tag twice, regardless of screener.
"""

from datetime import date, datetime

from sqlalchemy import UniqueConstraint
from sqlmodel import Field, SQLModel


class Tag(SQLModel, table=True):
    """A unique sector/industry label, e.g. 'auto ancillaries'."""

    __tablename__ = "tags"

    id: int | None = Field(default=None, primary_key=True)
    label: str = Field(
        max_length=100,
        unique=True,
        index=True,
        description="Lowercase tag label",
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)


class StockTag(SQLModel, table=True):
    """Junction linking a Stock to a Tag with provenance metadata.

    Tracks WHO tagged it (Gemini vs manual), WHEN, and from WHICH screener.
    """

    __tablename__ = "stock_tags"
    __table_args__ = (
        UniqueConstraint(
            "stock_id",
            "tag_id",
            name="uq_stock_tag",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    stock_id: int = Field(foreign_key="stocks.id", index=True)
    tag_id: int = Field(foreign_key="tags.id", index=True)
    screener_id: int = Field(foreign_key="screeners.id")
    tagged_on: date = Field(description="Date tag was assigned")
    source: str = Field(
        default="gemini",
        max_length=50,
        description="'gemini' for AI-generated, 'manual' for human-assigned",
    )
